controller_manager_ns: controller_manager
controller_list:
  - name: arm/arm_joint_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint101
      - joint102
      - joint103
      - joint104
      - joint105
      - joint106
      - joint201
      - joint202
      - joint203
      - joint204
      - joint205
      - joint206
