// Generated by gencpp from file cx_driver/motor_info.msg
// DO NOT EDIT!


#ifndef CX_DRIVER_MESSAGE_MOTOR_INFO_H
#define CX_DRIVER_MESSAGE_MOTOR_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cx_driver
{
template <class ContainerAllocator>
struct motor_info_
{
  typedef motor_info_<ContainerAllocator> Type;

  motor_info_()
    : id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , dlc(0)
    , data()  {
      data.assign(0);
  }
  motor_info_(const ContainerAllocator& _alloc)
    : id(0)
    , is_rtr(false)
    , is_extended(false)
    , is_error(false)
    , dlc(0)
    , data()  {
  (void)_alloc;
      data.assign(0);
  }



   typedef uint32_t _id_type;
  _id_type id;

   typedef uint8_t _is_rtr_type;
  _is_rtr_type is_rtr;

   typedef uint8_t _is_extended_type;
  _is_extended_type is_extended;

   typedef uint8_t _is_error_type;
  _is_error_type is_error;

   typedef uint8_t _dlc_type;
  _dlc_type dlc;

   typedef boost::array<uint8_t, 8>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::cx_driver::motor_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cx_driver::motor_info_<ContainerAllocator> const> ConstPtr;

}; // struct motor_info_

typedef ::cx_driver::motor_info_<std::allocator<void> > motor_info;

typedef boost::shared_ptr< ::cx_driver::motor_info > motor_infoPtr;
typedef boost::shared_ptr< ::cx_driver::motor_info const> motor_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cx_driver::motor_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cx_driver::motor_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cx_driver::motor_info_<ContainerAllocator1> & lhs, const ::cx_driver::motor_info_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.is_rtr == rhs.is_rtr &&
    lhs.is_extended == rhs.is_extended &&
    lhs.is_error == rhs.is_error &&
    lhs.dlc == rhs.dlc &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cx_driver::motor_info_<ContainerAllocator1> & lhs, const ::cx_driver::motor_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cx_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cx_driver::motor_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cx_driver::motor_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cx_driver::motor_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cx_driver::motor_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cx_driver::motor_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cx_driver::motor_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cx_driver::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e581c8420d38dcd98d0263cda11f3fb6";
  }

  static const char* value(const ::cx_driver::motor_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe581c8420d38dcd9ULL;
  static const uint64_t static_value2 = 0x8d0263cda11f3fb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cx_driver::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cx_driver/motor_info";
  }

  static const char* value(const ::cx_driver::motor_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cx_driver::motor_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"bool is_rtr\n"
"bool is_extended\n"
"bool is_error\n"
"uint8 dlc\n"
"uint8[8] data\n"
;
  }

  static const char* value(const ::cx_driver::motor_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cx_driver::motor_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.is_rtr);
      stream.next(m.is_extended);
      stream.next(m.is_error);
      stream.next(m.dlc);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cx_driver::motor_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cx_driver::motor_info_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "is_rtr: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_rtr);
    s << indent << "is_extended: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_extended);
    s << indent << "is_error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_error);
    s << indent << "dlc: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dlc);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CX_DRIVER_MESSAGE_MOTOR_INFO_H
